PROJNAME=RobottiProjekti
DEVICE=CY8C27443B
BASEDEVICE=CY8C27000B
PROJPATH=Z:/AMMATI~2/Koodi/Robor7/ROBOTT~1/ROBOTT~1
PSOCDIR=C:/PROGRA~2/Cypress/PSOCDE~1/5.4/Common/CY110F~1
INCLUDE_PATH=C:/PROGRA~2/Cypress/PSOCDE~1/5.4/Common/CY110F~1/tools/include/CY8C27~1
CSRCS= main.c motorcontrol.c ultracontrol.c
LIBCSRCS=
STDCSRCS=
ASMSRCS=
LIBASMSRCS= adcinc.asm adcincint.asm lcd.asm pga.asm psocconfig.asm psocconfigtbl.asm pwm8_oikea.asm pwm8_oikeaint.asm pwm8_servo.asm pwm8_servoint.asm pwm8_vasen.asm pwm8_vasenint.asm timer8.asm timer8int.asm
STDASMSRCS=
OBJECT_SOURCES= main.c motorcontrol.c ultracontrol.c
FILLVALUE=0x30
LASTROM=0x3fff
LASTRAM=0xff
CODECOMPRESSOR=
MORE_CFLAGS=-Wf-Osize 
RELSTART=0x150
INC_PATH=
CDEFINES=
LIBS=
UMLIBS=
LIB_PATH=
ENABLE_ALIGN_SHIFT=0
LMM=
SYS_INC_CONTENTS:=SYSTEM_STACK_PAGE:_equ_0 SYSTEM_STACK_BASE_ADDR:_equ_0h SYSTEM_LARGE_MEMORY_MODEL:_equ_0 SYSTEM_SMALL_MEMORY_MODEL:_equ_1 IMAGECRAFT:_equ_1 HITECH:_equ_2 TOOLCHAIN:_equ_IMAGECRAFT 
SYSTEM_TOOLS=1
CSFLOW=
CONFIG_NAMES=robottiprojekti 
