//*****************************************************************************
//*****************************************************************************
//  FILENAME: PWM8_VASEN.h
//   Version: 2.60, Updated on 2013/5/19 at 10:44:7
//  Generated by PSoC Designer 5.4.2946
//
//  DESCRIPTION: PWM8 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef PWM8_VASEN_INCLUDE
#define PWM8_VASEN_INCLUDE

#include <m8c.h>

#pragma fastcall16 PWM8_VASEN_EnableInt
#pragma fastcall16 PWM8_VASEN_DisableInt
#pragma fastcall16 PWM8_VASEN_Start
#pragma fastcall16 PWM8_VASEN_Stop
#pragma fastcall16 PWM8_VASEN_bReadCounter              // Read  DR0
#pragma fastcall16 PWM8_VASEN_WritePeriod               // Write DR1
#pragma fastcall16 PWM8_VASEN_bReadPulseWidth           // Read  DR2
#pragma fastcall16 PWM8_VASEN_WritePulseWidth           // Write DR2

// The following symbols are deprecated.
// They may be omitted in future releases
//
#pragma fastcall16 bPWM8_VASEN_ReadCounter              // Read  DR0 (Deprecated)
#pragma fastcall16 bPWM8_VASEN_ReadPulseWidth           // Read  DR2 (Deprecated)


//-------------------------------------------------
// Prototypes of the PWM8_VASEN API.
//-------------------------------------------------

extern void PWM8_VASEN_EnableInt(void);                        // Proxy Class 1
extern void PWM8_VASEN_DisableInt(void);                       // Proxy Class 1
extern void PWM8_VASEN_Start(void);                            // Proxy Class 1
extern void PWM8_VASEN_Stop(void);                             // Proxy Class 1
extern BYTE PWM8_VASEN_bReadCounter(void);                     // Proxy Class 2
extern void PWM8_VASEN_WritePeriod(BYTE bPeriod);              // Proxy Class 1
extern BYTE PWM8_VASEN_bReadPulseWidth(void);                  // Proxy Class 1
extern void PWM8_VASEN_WritePulseWidth(BYTE bPulseWidth);      // Proxy Class 1

// The following functions are deprecated.
// They may be omitted in future releases
//
extern BYTE bPWM8_VASEN_ReadCounter(void);            // Deprecated
extern BYTE bPWM8_VASEN_ReadPulseWidth(void);         // Deprecated


//--------------------------------------------------
// Constants for PWM8_VASEN API's.
//--------------------------------------------------

#define PWM8_VASEN_CONTROL_REG_START_BIT       ( 0x01 )
#define PWM8_VASEN_INT_REG_ADDR                ( 0x0e1 )
#define PWM8_VASEN_INT_MASK                    ( 0x01 )


//--------------------------------------------------
// Constants for PWM8_VASEN user defined values
//--------------------------------------------------

#define PWM8_VASEN_PERIOD                      ( 0xc7 )
#define PWM8_VASEN_PULSE_WIDTH                 ( 0x00 )


//-------------------------------------------------
// Register Addresses for PWM8_VASEN
//-------------------------------------------------

#pragma ioport  PWM8_VASEN_COUNTER_REG: 0x020              //DR0 Count register
BYTE            PWM8_VASEN_COUNTER_REG;
#pragma ioport  PWM8_VASEN_PERIOD_REG:  0x021              //DR1 Period register
BYTE            PWM8_VASEN_PERIOD_REG;
#pragma ioport  PWM8_VASEN_COMPARE_REG: 0x022              //DR2 Compare register
BYTE            PWM8_VASEN_COMPARE_REG;
#pragma ioport  PWM8_VASEN_CONTROL_REG: 0x023              //Control register
BYTE            PWM8_VASEN_CONTROL_REG;
#pragma ioport  PWM8_VASEN_FUNC_REG:    0x120              //Function register
BYTE            PWM8_VASEN_FUNC_REG;
#pragma ioport  PWM8_VASEN_INPUT_REG:   0x121              //Input register
BYTE            PWM8_VASEN_INPUT_REG;
#pragma ioport  PWM8_VASEN_OUTPUT_REG:  0x122              //Output register
BYTE            PWM8_VASEN_OUTPUT_REG;
#pragma ioport  PWM8_VASEN_INT_REG:       0x0e1            //Interrupt Mask Register
BYTE            PWM8_VASEN_INT_REG;


//-------------------------------------------------
// PWM8_VASEN Macro 'Functions'
//-------------------------------------------------

#define PWM8_VASEN_Start_M \
   PWM8_VASEN_CONTROL_REG |=  PWM8_VASEN_CONTROL_REG_START_BIT

#define PWM8_VASEN_Stop_M  \
   PWM8_VASEN_CONTROL_REG &= ~PWM8_VASEN_CONTROL_REG_START_BIT

#define PWM8_VASEN_EnableInt_M   \
   M8C_EnableIntMask(PWM8_VASEN_INT_REG, PWM8_VASEN_INT_MASK)

#define PWM8_VASEN_DisableInt_M  \
   M8C_DisableIntMask(PWM8_VASEN_INT_REG, PWM8_VASEN_INT_MASK)

#endif
// end of file PWM8_VASEN.h
